# Generated by Django 2.2.6 on 2019-10-25 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id_facility', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('deadline', models.TimeField()),
                ('max_ordered_meals', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=320)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('diet_type', models.CharField(choices=[('n', 'normal'), ('v', 'vegetarian'), ('g', 'gluten-free')], default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('max_items', models.IntegerField(default=10)),
                ('type', models.CharField(choices=[('d', 'Daily'), ('s', 'Static')], default='s', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('email', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('profile_info', models.CharField(max_length=300)),
                ('image', models.ImageField(max_length=50, upload_to='')),
                ('login', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('Person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='canteen.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Registered', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='canteen.Registered')),
                ('role', models.CharField(choices=[('a', 'administrator'), ('o', 'operator'), ('d', 'driver')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Item')),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Menu')),
            ],
            options={
                'unique_together': {('id_menu', 'id_item')},
            },
        ),
        migrations.CreateModel(
            name='Food_order',
            fields=[
                ('id_food_order', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_paid', models.DateTimeField()),
                ('date_approved', models.DateTimeField()),
                ('date_delivered', models.DateTimeField()),
                ('status', models.CharField(choices=[('o', 'ordered'), ('a', 'approved'), ('c', 'canceled'), ('d', 'delivered')], default='o', max_length=1)),
                ('payment_form', models.CharField(choices=[('m', 'meal ticket'), ('n', 'card now'), ('d', 'card on delivery'), ('h', 'cash on delivery')], default='h', max_length=1)),
                ('Facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Facility')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Person')),
                ('Approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Approved_by', to='canteen.Employee')),
                ('Delivered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Delivered_by', to='canteen.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Facility_menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Facility')),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Menu')),
            ],
            options={
                'unique_together': {('id_facility', 'id_menu')},
            },
        ),
    ]
