# Generated by Django 2.2.2 on 2019-11-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='is_operator',
            field=models.BooleanField(default=False),
        ),
    ]
