# Generated by Django 2.2.2 on 2019-11-09 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_auto_20191103_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='testItem',
            fields=[
                ('id_testItem', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('Facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='testOrder',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('testItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.testItem')),
            ],
        ),
    ]
