# Generated by Django 2.2.6 on 2019-11-10 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0004_testitem_testorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Registered',
            new_name='registered',
        ),
        migrations.RenameField(
            model_name='food_order',
            old_name='Facility',
            new_name='facility',
        ),
        migrations.RenameField(
            model_name='food_order',
            old_name='Person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='registered',
            old_name='Person',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='food_order',
            name='Approved_by',
        ),
        migrations.RemoveField(
            model_name='food_order',
            name='Delivered_by',
        ),
        migrations.AddField(
            model_name='food_order',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Approved_by', to='canteen.Employee'),
        ),
        migrations.AddField(
            model_name='food_order',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Delivered_by', to='canteen.Employee'),
        ),
        migrations.AlterField(
            model_name='food_order',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food_order',
            name='date_delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food_order',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registered',
            name='image',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='registered',
            name='profile_info',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Food_order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_food_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Food_order')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Item')),
            ],
            options={
                'unique_together': {('id_food_order', 'id_item')},
            },
        ),
    ]
