# Generated by Django 2.2.2 on 2019-11-17 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0008_auto_20191117_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_order',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canteen.Person'),
        ),
    ]
