# Generated by Django 2.2.2 on 2019-11-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0009_auto_20191117_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='food_order_item',
            unique_together=set(),
        ),
    ]
