# Generated by Django 2.2.2 on 2019-11-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0010_auto_20191124_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_order',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canteen.Facility'),
        ),
    ]
