# Generated by Django 2.2.2 on 2019-11-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_auto_20191126_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testitem',
            name='Facility',
        ),
        migrations.DeleteModel(
            name='testOrder',
        ),
        migrations.AddField(
            model_name='food_order_item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='testItem',
        ),
    ]
