# Generated by Django 2.2.2 on 2019-11-28 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0005_person_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_order',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Approved_by', to='canteen.Person'),
        ),
        migrations.AlterField(
            model_name='food_order',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Delivered_by', to='canteen.Person'),
        ),
    ]
