# Generated by Django 2.2.2 on 2019-11-29 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0006_auto_20191129_0007'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='food_order_item',
            unique_together={('id_food_order', 'id_item')},
        ),
    ]
