# Generated by Django 2.2.2 on 2019-11-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0008_auto_20191129_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='telephone',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
